server:
  port: 8080

logging:
  level:
    org.springframework.orm.jpa: TRACE
    org.springframework.transaction: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: TRACE
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6542/ewm-main
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

ewm:
  main-service:
    name: ewm-main
  stats-service:
    url: http://localhost:9090